package MJPEG;

public interface Resize {
  /* ResizeFactor[0][0] = WindowHeight */
  /* ResizeFactor[0][1] = WindowWidth  */
  /* ResizeFactor[x][0] = WindowHeight for stream in position x */
  /* ResizeFactor[x][1] = WindowWidth for stream in position x  */
  void resize      (int video_id, int frame_id, void* buffer);
}

