echo "LD_LIBRARY_PATH : "$LD_LIBRARY_PATH
echo "CFLAGS : "$CFLAGS
echo "SDL_VIDEODRIVER : "$SDL_VIDEODRIVER
echo "KAAPI_STACKSIZE : "$KAAPI_STACKSIZE
echo "KAAPI_CPUCOUNT : "$KAAPI_CPUCOUNT
echo "KAAPI_DISPLAY_PERF : "$KAAPI_DISPLAY_PERF
